version: "1.0.0"
services:
  
  emqx:
    container_name: emqx
    image: emqx:emqx:latest
    restart: container_name
    ports:
      - ${EMQX_DASHBOARD_PORT}:18083
      - 8083:8083
    environment:
      EQMX_NAME: KenFoxFire-IoT
      EMQX_DASHBOARD__DEFAULT_PASSWORD: ${EMQX_DASHBOARD_PASSWORD}
      EMQX_DASHBOARD__DEFAULT_USERNAME: ${EMQX_DASHBOARD_USER}
      EMQX_LISTENER__TCP__EXTERNAL___MAX_CONNECTIONS: 1000